# Generated by Django 4.1.1 on 2022-11-29 11:55

from django.db import migrations, models
import freeboard.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='댓글내용')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('deleted', models.BooleanField(default=False, verbose_name='삭제여부')),
                ('reply', models.IntegerField(default=0, verbose_name='답글위치')),
            ],
            options={
                'verbose_name': '자유게시판 댓글',
                'verbose_name_plural': 'comments',
                'db_table': 'comment',
            },
        ),
        migrations.CreateModel(
            name='Freeboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='제목')),
                ('content', models.TextField(verbose_name='내용')),
                ('category', models.CharField(choices=[('자유', '자유'), ('GSHS', '학교'), ('LINUX', '리눅스'), ('WINDOW', '윈도우')], default='자유', max_length=18, verbose_name='분류')),
                ('upload_files', models.FileField(blank=True, null=True, upload_to=freeboard.models.get_file_path, verbose_name='파일')),
                ('filename', models.CharField(max_length=64, null=True, verbose_name='첨부파일명')),
                ('hits', models.PositiveIntegerField(default=0, verbose_name='조회수')),
                ('comments', models.PositiveIntegerField(null=True, verbose_name='댓글수')),
                ('registered_date', models.DateTimeField(auto_now_add=True, verbose_name='등록시간')),
                ('top_fixed', models.BooleanField(default=False, verbose_name='상단고정')),
            ],
            options={
                'db_table': 'freeboard',
            },
        ),
    ]
