# Generated by Django 4.1.1 on 2022-11-08 10:00

from django.db import migrations, models
import freeboard.models


class Migration(migrations.Migration):

    dependencies = [
        ('freeboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='freeboard',
            name='filename',
            field=models.CharField(max_length=64, null=True, verbose_name='첨부파일명'),
        ),
        migrations.AddField(
            model_name='freeboard',
            name='upload_files',
            field=models.FileField(blank=True, null=True, upload_to=freeboard.models.get_file_path, verbose_name='파일'),
        ),
    ]
