# Generated by Django 4.1.1 on 2022-11-08 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freeboard', '0002_freeboard_filename_freeboard_upload_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freeboard',
            name='upload_files',
            field=models.FileField(blank=True, null=True, upload_to='images/%Y/%m/%d/', verbose_name='파일'),
        ),
    ]
