# Generated by Django 4.1.1 on 2022-12-07 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freeboard', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': '게시판 댓글', 'verbose_name_plural': 'comments'},
        ),
        migrations.AlterField(
            model_name='freeboard',
            name='category',
            field=models.CharField(choices=[('자유', '자유'), ('GSHS', '학교'), ('LINUX', '리눅스'), ('WINDOW', '윈도우'), ('CODE', '프로그램')], default='자유', max_length=18, verbose_name='분류'),
        ),
    ]
