# Generated by Django 4.1.1 on 2022-11-14 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freeboard', '0005_free_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Free',
        ),
        migrations.AddField(
            model_name='freeboard',
            name='comments',
            field=models.PositiveIntegerField(null=True, verbose_name='댓글수'),
        ),
    ]
