# Generated by Django 4.1.1 on 2022-11-15 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freeboard', '0007_alter_freeboard_registered_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='reply',
            field=models.IntegerField(default=0, verbose_name='답글위치'),
        ),
        migrations.AddField(
            model_name='freeboard',
            name='category',
            field=models.CharField(choices=[('자유', '자유'), ('GSHS', '학교'), ('LINUX', '리눅스'), ('WINDOW', '윈도우')], default='자유', max_length=18, verbose_name='분류'),
        ),
    ]
