# Generated by Django 4.1.1 on 2022-09-23 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subject',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
