# Generated by Django 4.1.1 on 2022-11-03 12:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buyproduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buydate', models.DateField(default=django.utils.timezone.now)),
                ('company', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=30)),
                ('bigo', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'buyproduct',
            },
        ),
        migrations.CreateModel(
            name='Change_Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/%Y/%m/%d/')),
            ],
            options={
                'db_table': 'change_Photo',
            },
        ),
        migrations.CreateModel(
            name='Gigiinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(blank=True, max_length=20, null=True)),
                ('color', models.CharField(blank=True, choices=[('None', None), ('블랙', '블랙'), ('컬러', '컬러')], default=None, max_length=10)),
                ('jaego', models.BooleanField(default=False)),
                ('notuse', models.BooleanField(default=False)),
                ('bigo', models.CharField(blank=True, max_length=100, null=True)),
                ('buyproduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gigiinfo', to='gshsapp.buyproduct')),
            ],
            options={
                'db_table': 'gigiinfo',
            },
        ),
        migrations.CreateModel(
            name='Gubun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tablename', models.CharField(choices=[('Buyproduct', '구매Table'), ('Replacement', '교체Table')], default='', max_length=20)),
                ('gubun', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'gubun',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building', models.CharField(max_length=50)),
                ('hosil', models.CharField(max_length=20)),
                ('locationgubun', models.CharField(choices=[('부서', '부서'), ('강의실', '강의실'), ('실험실', '실험실'), ('협의회실', '협의회실'), ('강당', '강당'), ('기타', '기타')], default='기타', max_length=20)),
                ('bigo', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'location',
            },
        ),
        migrations.CreateModel(
            name='Repair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('problem', models.CharField(max_length=50)),
                ('result', models.CharField(max_length=50)),
                ('cost', models.PositiveIntegerField(default=0)),
                ('bigo', models.CharField(blank=True, max_length=100, null=True)),
                ('gigiinfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repair', to='gshsapp.gigiinfo')),
            ],
            options={
                'db_table': 'repair',
            },
        ),
        migrations.CreateModel(
            name='Replacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('count', models.PositiveSmallIntegerField(default=1)),
                ('cost', models.PositiveIntegerField(default=0)),
                ('bigo', models.CharField(blank=True, max_length=100, null=True)),
                ('gigiinfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replacement', to='gshsapp.gigiinfo')),
                ('gubun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replacement', to='gshsapp.gubun')),
            ],
            options={
                'db_table': 'replacement',
            },
        ),
        migrations.CreateModel(
            name='Repair_Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/%Y/%m/%d/')),
                ('repair', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='repair_photo', to='gshsapp.repair')),
            ],
            options={
                'db_table': 'repair_Photo',
            },
        ),
        migrations.AddField(
            model_name='gigiinfo',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gigiinfo', to='gshsapp.location'),
        ),
    ]
