# Generated by Django 4.1.1 on 2022-09-29 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gshsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gubun',
            name='tablename',
            field=models.CharField(default='', max_length=20),
        ),
    ]
