# Generated by Django 4.1.1 on 2022-09-29 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gshsapp', '0002_gubun_tablename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyproduct',
            name='bigo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='gigiinfo',
            name='bigo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='bigo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='repair',
            name='bigo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='replacement',
            name='bigo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
