# Generated by Django 4.1.1 on 2022-09-29 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gshsapp', '0003_alter_buyproduct_bigo_alter_gigiinfo_bigo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='lcategory',
        ),
    ]
