# Generated by Django 4.1.1 on 2022-09-29 10:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gshsapp', '0004_remove_location_lcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gigiinfo',
            name='ip',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='gigiinfo',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gigiinfo', to=settings.AUTH_USER_MODEL),
        ),
    ]
