# Generated by Django 4.1.1 on 2022-12-01 10:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gshsapp', '0004_remove_repair_location_remove_replacement_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyproduct',
            name='buydate',
        ),
        migrations.AddField(
            model_name='gigiinfo',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='location',
            name='locationgubun',
            field=models.CharField(choices=[('부서', '부서'), ('강의실', '강의실'), ('실험실', '실험실'), ('협의회실', '협의회실'), ('강당', '강당'), ('서버실', '서버실'), ('영양사실', '영양사실'), ('Wee클래스', 'Wee클래스'), ('급식실', '급식실'), ('동아리실', '동아리실'), ('기타', '기타')], default='기타', max_length=20),
        ),
    ]
