# Generated by Django 4.1.1 on 2022-12-07 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gshsapp', '0005_remove_buyproduct_buydate_gigiinfo_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyproduct',
            name='model',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='locationgubun',
            field=models.CharField(choices=[('부서', '부서'), ('강의실', '강의실'), ('실험실', '실험실'), ('협의회실', '협의회실'), ('강당', '강당'), ('서버실', '서버실'), ('동아리실', '동아리실'), ('기타', '기타')], default='기타', max_length=20),
        ),
    ]
