# Generated by Django 4.1.1 on 2022-10-04 19:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gshsapp', '0006_repair_cost_repair_image_replacement_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyproduct',
            name='buydate',
            field=models.DateField(default=datetime.datetime(2022, 10, 4, 19, 57, 11, 238268)),
        ),
    ]
