# Generated by Django 4.1.1 on 2022-10-04 19:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gshsapp', '0007_buyproduct_buydate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyproduct',
            name='buydate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
