# Generated by Django 4.1.1 on 2022-10-05 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gshsapp', '0008_alter_buyproduct_buydate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gigiinfo',
            name='color',
            field=models.CharField(default='블랙', max_length=5),
        ),
    ]
