# Generated by Django 4.1.1 on 2022-10-07 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gshsapp', '0011_alter_gigiinfo_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gigiinfo',
            name='color',
            field=models.CharField(blank=True, choices=[('블랙', '블랙'), ('컬러', '컬러')], default='블랙', max_length=10),
        ),
        migrations.AlterField(
            model_name='replacement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='replacement/%Y/%m/%d'),
        ),
    ]
