# Generated by Django 4.1.1 on 2022-10-07 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gshsapp', '0012_alter_gigiinfo_color_alter_replacement_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='locationgubun',
            field=models.CharField(choices=[('강의실', '강의실'), ('실험실', '실험실'), ('협의회실', '협의회실'), ('강당', '강당'), ('기타', '기타')], default='기타', max_length=20),
        ),
    ]
