# Generated by Django 4.1.1 on 2022-10-11 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gshsapp', '0014_remove_repair_image_remove_replacement_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='change_photo',
            name='replacement',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='change_photo', to='gshsapp.replacement'),
        ),
        migrations.AlterField(
            model_name='repair_photo',
            name='repair',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='repair_photo', to='gshsapp.repair'),
        ),
    ]
