# Generated by Django 4.1.1 on 2022-10-21 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gshsapp', '0015_alter_change_photo_replacement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gigiinfo',
            name='color',
            field=models.CharField(blank=True, choices=[('None', None), ('블랙', '블랙'), ('컬러', '컬러')], default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='gubun',
            name='tablename',
            field=models.CharField(choices=[('구매Table', 'Buyproduct'), ('교체Table', 'Replacement')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='location',
            name='locationgubun',
            field=models.CharField(choices=[('부서', '부서'), ('강의실', '강의실'), ('실험실', '실험실'), ('협의회실', '협의회실'), ('강당', '강당'), ('기타', '기타')], default='기타', max_length=20),
        ),
    ]
