# Generated by Django 4.1.1 on 2022-10-21 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gshsapp', '0016_alter_gigiinfo_color_alter_gubun_tablename_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gubun',
            name='tablename',
            field=models.CharField(choices=[('Buyproduct', '구매Table'), ('Replacement', '교체Table')], default='', max_length=20),
        ),
    ]
